In [1]:
import urllib
import numpy as np

In [4]:
def parseData(fname):
    for l in urllib.request.urlopen(fname):
        yield eval(l)

In [6]:
data = list(parseData("http://jmcauley.ucsd.edu/cse255/data/beer/beer_50000.json"))

In [23]:
type(data[0]), data[0]

(dict,
 {'beer/ABV': 5.0,
  'beer/beerId': '47986',
  'beer/brewerId': '10325',
  'beer/name': 'Sausa Weizen',
  'beer/style': 'Hefeweizen',
  'review/appearance': 2.5,
  'review/aroma': 2.0,
  'review/overall': 1.5,
  'review/palate': 1.5,
  'review/taste': 1.5,
  'review/text': 'A lot of foam. But a lot.\tIn the smell some banana, and then lactic and tart. Not a good start.\tQuite dark orange in color, with a lively carbonation (now visible, under the foam).\tAgain tending to lactic sourness.\tSame for the taste. With some yeast and banana.',
  'review/timeStruct': {'hour': 20,
   'isdst': 0,
   'mday': 16,
   'min': 57,
   'mon': 2,
   'sec': 3,
   'wday': 0,
   'yday': 47,
   'year': 2009},
  'review/timeUnix': 1234817823,
  'user/profileName': 'stcules'})

In [14]:
data[2]['review/taste']

3.0

In [15]:
reviews = {}

In [18]:
for d in data:
    reviews[d['review/taste']] = reviews.get(d['review/taste'], 0) + 1

In [19]:
reviews

{1.0: 211,
 1.5: 343,
 2.0: 1099,
 2.5: 1624,
 3.0: 4137,
 3.5: 8797,
 4.0: 16575,
 4.5: 12883,
 5.0: 4331}

In [37]:
feature1 = [d['beer/style']=='Hefeweizen' for d in data]
feature2 = [d['beer/ABV'] for d in data]
target = [d['review/taste'] for d in data]

In [49]:
theta

array([[0.3104749 ],
       [0.56378572],
       [0.91179738]])

In [47]:
X = np.stack((np.ones(len(data)), feature1, feature2), -1)
Y = np.array(target).reshape(-1, 1)
theta = np.random.rand(3, 1)

In [48]:
X.shape, Y.shape, theta.shape

((50000, 3), (50000, 1), (3, 1))

In [58]:
theta,residuals, _, _ = np.linalg.lstsq(X, Y)

/home/fanjin/.local/lib/python3.5/site-packages/ipykernel_launcher.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  """Entry point for launching an IPython kernel.


In [59]:
theta, residuals

(array([[ 1.88556594e+12],
        [-1.88556594e+12],
        [-1.88556594e+12]]), array([25622.62506767]))

In [51]:
def split_data(X, Y, holdout_ratio, shuffle=False):
    m = X.shape[0]
    m_holdout = int(m * holdout_ratio)
    
    if shuffle:
        permutation = np.random.permutation(m)
        X_shuffle = X[permutation, :]
        Y_shuffle = Y[permutation, :]
        
    return X[:-m_holdout, :], Y[:-m_holdout, :], X[-m_holdout:, :], Y[-m_holdout:, :]

In [56]:
feature1 = [d['beer/style']=='Hefeweizen' for d in data]
feature2 = [d['beer/style']!='Hefeweizen' for d in data]
X = np.stack((np.ones(len(data)), feature1, feature2), -1)
theta = np.random.rand(3, 1)

In [55]:
X

array([[1., 1., 0.],
       [1., 0., 1.],
       [1., 0., 1.],
       ...,
       [1., 0., 1.],
       [1., 0., 1.],
       [1., 0., 1.]])